### ISSUE TITLE
Advanced search bar is static causing overlapping text

### ISSUE THREAD

**Issue by linaxieNZ** [openlawnz/openlawnz-website#8]
Advanced search bar is static when scrolling through the results page and this causes overlapping test with the Search Tips.

![advanced search bar](https://user-images.githubusercontent.com/26584515/91637061-97eb7180-ea59-11ea-96c6-eb40201c57fb.PNG)

**Comment by williamparry** [comment]
Think this is fixed - could you re-test please?

**Comment by royastro-upstream** [comment]
Still happening @williamparry but raised a PR to resolve this.

**Comment by williamparry** [comment]
Hmm I'm not sure - looks like a `position: sticky` thing to me.

**Comment by linoypaul01** [comment]
@linaxieNZ  Please let me know the steps to reproduce.
